using System;
using System.Collections.Generic;

namespace case_study.Model
{
    public partial class AuditEquity
    {
        public string? Username { get; set; }
        public DateTime? Xndate { get; set; }
        public string? XnAction { get; set; }
        public string? EquityId { get; set; }
        public string? OldSecurityName { get; set; }
        public string? NewSecurityName { get; set; }
        public string? OldSecurityDescription { get; set; }
        public string? NewSecurityDescription { get; set; }
        public bool? OldHasPosistion { get; set; }
        public bool? NewHasPosistion { get; set; }
        public bool? OldIsActive { get; set; }
        public bool? NewIsActive { get; set; }
        public double? OldLotSize { get; set; }
        public double? NewLotSize { get; set; }
        public string? OldBbgUniqueName { get; set; }
        public string? NewBbgUniqueName { get; set; }
        public string? OldCusip { get; set; }
        public string? NewCusip { get; set; }
        public string? OldIsin { get; set; }
        public string? NewIsin { get; set; }
        public string? OldSedol { get; set; }
        public string? NewSedol { get; set; }
        public string? OldBloombergTicker { get; set; }
        public string? NewBloombergTicker { get; set; }
        public string? OldBbgUniqueId { get; set; }
        public string? NewBbgUniqueId { get; set; }
        public string? OldBbgGlobalId { get; set; }
        public string? NewBbgGlobalId { get; set; }
        public string? OldTickerAndExcahnge { get; set; }
        public string? NewTickerAndExcahnge { get; set; }
        public bool? OldIsAdr { get; set; }
        public bool? NewIsAdr { get; set; }
        public string? OldAdrUnderlyingTicker { get; set; }
        public string? NewAdrUnderlyingTicker { get; set; }
        public string? OldAdrUnderlyingCurrency { get; set; }
        public string? NewAdrUnderlyingCurrency { get; set; }
        public string? OldSharesPerAdr { get; set; }
        public string? NewSharesPerAdr { get; set; }
        public DateTime? OldIpoDate { get; set; }
        public DateTime? NewIpoDate { get; set; }
        public string? OldPricingCurrency { get; set; }
        public string? NewPricingCurrency { get; set; }
        public long? OldSettleDays { get; set; }
        public long? NewSettleDays { get; set; }
        public double? OldTotalSharesOutstading { get; set; }
        public double? NewTotalSharesOutstading { get; set; }
        public double? OldVotingRightsPerShare { get; set; }
        public double? NewVotingRightsPerShare { get; set; }
        public double? OldAvgVol20d { get; set; }
        public double? NewAvgVol20d { get; set; }
        public double? OldBeta { get; set; }
        public double? NewBeta { get; set; }
        public double? OldShortIntrest { get; set; }
        public double? NewShortIntrest { get; set; }
        public double? OldReturnYtd { get; set; }
        public double? NewReturnYtd { get; set; }
        public double? OldVolatility90d { get; set; }
        public double? NewVolatility90d { get; set; }
        public string? OldPfAssetClass { get; set; }
        public string? NewPfAssetClass { get; set; }
        public string? OldPfCountry { get; set; }
        public string? NewPfCountry { get; set; }
        public string? OldPfCreditRating { get; set; }
        public string? NewPfCreditRating { get; set; }
        public string? OldPfCurrency { get; set; }
        public string? NewPfCurrency { get; set; }
        public string? OldPfInstrument { get; set; }
        public string? NewPfInstrument { get; set; }
        public string? OldPfLiquidityProfile { get; set; }
        public string? NewPfLiquidityProfile { get; set; }
        public string? OldPfMaturity { get; set; }
        public string? NewPfMaturity { get; set; }
        public string? OldPfNaicsCode { get; set; }
        public string? NewPfNaicsCode { get; set; }
        public string? OldPfRegion { get; set; }
        public string? NewPfRegion { get; set; }
        public string? OldPfSector { get; set; }
        public string? NewPfSector { get; set; }
        public string? OldPfSubAssetClass { get; set; }
        public string? NewPfSubAssetClass { get; set; }
        public string? OldIssueCountry { get; set; }
        public string? NewIssueCountry { get; set; }
        public string? OldExchange { get; set; }
        public string? NewExchange { get; set; }
        public string? OldIssuer { get; set; }
        public string? NewIssuer { get; set; }
        public string? OldIssueCurrency { get; set; }
        public string? NewIssueCurrency { get; set; }
        public string? OldTradingCurrency { get; set; }
        public string? NewTradingCurrency { get; set; }
        public string? OldBbgIndustrySubGroup { get; set; }
        public string? NewBbgIndustrySubGroup { get; set; }
        public string? OldBbgIndustryGroup { get; set; }
        public string? NewBbgIndustryGroup { get; set; }
        public string? OldBbgSector { get; set; }
        public string? NewBbgSector { get; set; }
        public string? OldCountryOfIncorporation { get; set; }
        public string? NewCountryOfIncorporation { get; set; }
        public string? OldRiskCurrency { get; set; }
        public string? NewRiskCurrency { get; set; }
        public double? OldOpenPrice { get; set; }
        public double? NewOpenPrice { get; set; }
        public double? OldClosePrice { get; set; }
        public double? NewClosePrice { get; set; }
        public double? OldVolume { get; set; }
        public double? NewVolume { get; set; }
        public double? OldLastPrice { get; set; }
        public double? NewLastPrice { get; set; }
        public double? OldAskPrice { get; set; }
        public double? NewAskPrice { get; set; }
        public double? OldBidPrice { get; set; }
        public double? NewBidPrice { get; set; }
        public double? OldPeRatio { get; set; }
        public double? NewPeRatio { get; set; }
        public DateTime? OldDividendDeclaredDate { get; set; }
        public DateTime? NewDividendDeclaredDate { get; set; }
        public DateTime? OldDividendExDate { get; set; }
        public DateTime? NewDividendExDate { get; set; }
        public DateTime? OldDividendRecordDate { get; set; }
        public DateTime? NewDividendRecordDate { get; set; }
        public DateTime? OldDividendPayDate { get; set; }
        public DateTime? NewDividendPayDate { get; set; }
        public double? OldDividendAmount { get; set; }
        public double? NewDividendAmount { get; set; }
        public string? OldFrequency { get; set; }
        public string? NewFrequency { get; set; }
        public string? OldDividendType { get; set; }
        public string? NewDividendType { get; set; }
    }
}
