using System;
using System.Collections.Generic;

namespace case_study.Model
{
    public partial class AuditBond
    {
        public int XnId { get; set; }
        public DateTime? XnDate { get; set; }
        public string? XnAction { get; set; }
        public string? Username { get; set; }
        public string? SecurityId { get; set; }
        public string? OldSecurityName { get; set; }
        public string? NewSecurityName { get; set; }
        public string? OldSecurityDescription { get; set; }
        public string? NewSecurityDescription { get; set; }
        public string? OldAssetType { get; set; }
        public string? NewAssetType { get; set; }
        public string? OldInvestmentType { get; set; }
        public string? NewInvestmentType { get; set; }
        public double? OldTradingFactor { get; set; }
        public double? NewTradingFactor { get; set; }
        public double? OldPricingFactor { get; set; }
        public double? NewPricingFactor { get; set; }
        public string? OldIsin { get; set; }
        public string? NewIsin { get; set; }
        public string? OldBloombergTicker { get; set; }
        public string? NewBloombergTicker { get; set; }
        public string? OldBloombergUniqueId { get; set; }
        public string? NewBloombergUniqueId { get; set; }
        public string? OldCusip { get; set; }
        public string? NewCusip { get; set; }
        public string? OldSedol { get; set; }
        public string? NewSedol { get; set; }
        public DateTime? OldFirstCouponDate { get; set; }
        public DateTime? NewFirstCouponDate { get; set; }
        public double? OldCouponCap { get; set; }
        public double? NewCouponCap { get; set; }
        public double? OldCouponFloor { get; set; }
        public double? NewCouponFloor { get; set; }
        public double? OldCouponFrequency { get; set; }
        public double? NewCouponFrequency { get; set; }
        public double? OldCouponRate { get; set; }
        public double? NewCouponRate { get; set; }
        public string? OldCouponType { get; set; }
        public string? NewCouponType { get; set; }
        public double? OldFloatSpread { get; set; }
        public double? NewFloatSpread { get; set; }
        public bool? OldIsCallable { get; set; }
        public bool? NewIsCallable { get; set; }
        public bool? OldIsFixToFloat { get; set; }
        public bool? NewIsFixToFloat { get; set; }
        public bool? OldIsPutable { get; set; }
        public bool? NewIsPutable { get; set; }
        public DateTime? OldIssueDate { get; set; }
        public DateTime? NewIssueDate { get; set; }
        public DateTime? OldLastResetDate { get; set; }
        public DateTime? NewLastResetDate { get; set; }
        public DateTime? OldMaturityDate { get; set; }
        public DateTime? NewMaturityDate { get; set; }
        public double? OldMaxCallNoticeDays { get; set; }
        public double? NewMaxCallNoticeDays { get; set; }
        public double? OldMaxPutNoticeDays { get; set; }
        public double? NewMaxPutNoticeDays { get; set; }
        public DateTime? OldPenultimateCouponDate { get; set; }
        public DateTime? NewPenultimateCouponDate { get; set; }
        public double? OldResetFrequency { get; set; }
        public double? NewResetFrequency { get; set; }
        public bool? OldHasPosition { get; set; }
        public bool? NewHasPosition { get; set; }
        public double? OldDuration { get; set; }
        public double? NewDuration { get; set; }
        public double? OldVolatility30Days { get; set; }
        public double? NewVolatility30Days { get; set; }
        public double? OldVolatility90Days { get; set; }
        public double? NewVolatility90Days { get; set; }
        public double? OldConvexity { get; set; }
        public double? NewConvexity { get; set; }
        public double? OldAvgVolume30Days { get; set; }
        public double? NewAvgVolume30Days { get; set; }
        public string? OldPfassetClass { get; set; }
        public string? NewPfassetClass { get; set; }
        public string? OldPfcountry { get; set; }
        public string? NewPfcountry { get; set; }
        public string? OldPfcreditRating { get; set; }
        public string? NewPfcreditRating { get; set; }
        public string? OldPfcurrency { get; set; }
        public string? NewPfcurrency { get; set; }
        public string? OldPfinstrument { get; set; }
        public string? NewPfinstrument { get; set; }
        public string? OldPfliquidityProfile { get; set; }
        public string? NewPfliquidityProfile { get; set; }
        public string? OldPfmaturity { get; set; }
        public string? NewPfmaturity { get; set; }
        public string? OldPfnaicscode { get; set; }
        public string? NewPfnaicscode { get; set; }
        public string? OldPfregion { get; set; }
        public string? NewPfregion { get; set; }
        public string? OldPfsector { get; set; }
        public string? NewPfsector { get; set; }
        public string? OldPfsubAssetClass { get; set; }
        public string? NewPfsubAssetClass { get; set; }
        public string? OldBloombergIndustryGroup { get; set; }
        public string? NewBloombergIndustryGroup { get; set; }
        public string? OldBloombergIndustrySubGroup { get; set; }
        public string? NewBloombergIndustrySubGroup { get; set; }
        public string? OldBloombergIndustrySector { get; set; }
        public string? NewBloombergIndustrySector { get; set; }
        public string? OldIssueCountry { get; set; }
        public string? NewIssueCountry { get; set; }
        public string? OldIssueCurrency { get; set; }
        public string? NewIssueCurrency { get; set; }
        public string? OldIssuer { get; set; }
        public string? NewIssuer { get; set; }
        public string? OldRiskCurrency { get; set; }
        public string? NewRiskCurrency { get; set; }
        public DateTime? OldPutDate { get; set; }
        public DateTime? NewPutDate { get; set; }
        public double? OldPutPrice { get; set; }
        public double? NewPutPrice { get; set; }
        public double? OldAskPrice { get; set; }
        public double? NewAskPrice { get; set; }
        public double? OldHighPrice { get; set; }
        public double? NewHighPrice { get; set; }
        public double? OldLowPrice { get; set; }
        public double? NewLowPrice { get; set; }
        public double? OldOpenPrice { get; set; }
        public double? NewOpenPrice { get; set; }
        public double? OldVolume { get; set; }
        public double? NewVolume { get; set; }
        public double? OldBidPrice { get; set; }
        public double? NewBidPrice { get; set; }
        public double? OldLastPrice { get; set; }
        public double? NewLastPrice { get; set; }
        public DateTime? OldCallDate { get; set; }
        public DateTime? NewCallDate { get; set; }
        public double? OldCallPrice { get; set; }
        public double? NewCallPrice { get; set; }
    }
}
